version: "3.7"

services:
  develop:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:docker

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./src/postgres/db-init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8000:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
    external: true