version: "3.7"
services:
  develop:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: nodemon -L src/server.js

  # prod:
  #   build: .
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3000:3000
  #   command: npm run start:prod
    

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: db-test
      POSTGRES_USER: test1
      POSTGRES_PASSWORD: test1
    ports:
      - 8000:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
